@startuml Dinosaurio

class Ventana 
class Dibujo
class Sprite
class Actualizable

class Juego
class Dinosaurio
class Obstaculo
class Personaje
class Ave
class Escenario
class Puntuacion

Sprite "1" *- "*" Dibujo

Juego *-Dinosaurio
Juego *- Escenario
Dinosaurio *- Puntuacion 
Escenario *- Obstaculo

Ave -|> Obstaculo
Dinosaurio -|> Personaje

Dinosaurio o- Obstaculo

Personaje -|> Sprite

Ventana "1" o-- "*" Dibujo
Ventana -- Actualizable

@enduml